/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as IncomeCalculatorRouteImport } from './routes/income-calculator'
import { Route as DriveRouteImport } from './routes/drive'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MeetingsIndexRouteImport } from './routes/meetings.index'
import { Route as SdrSharedRouteImport } from './routes/sdr.shared'
import { Route as SdrReportsRouteImport } from './routes/sdr.reports'
import { Route as SdrCallsRouteImport } from './routes/sdr.calls'
import { Route as MeetingsPreparationRouteImport } from './routes/meetings.preparation'
import { Route as CrmDealsRouteImport } from './routes/crm.deals'
import { Route as CrmContactsRouteImport } from './routes/crm.contacts'
import { Route as CrmCompaniesRouteImport } from './routes/crm.companies'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTeamsRouteImport } from './routes/admin.teams'
import { Route as AdminSolutionsRouteImport } from './routes/admin.solutions'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomeCalculatorRoute = IncomeCalculatorRouteImport.update({
  id: '/income-calculator',
  path: '/income-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveRoute = DriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsIndexRoute = MeetingsIndexRouteImport.update({
  id: '/meetings/',
  path: '/meetings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SdrSharedRoute = SdrSharedRouteImport.update({
  id: '/sdr/shared',
  path: '/sdr/shared',
  getParentRoute: () => rootRouteImport,
} as any)
const SdrReportsRoute = SdrReportsRouteImport.update({
  id: '/sdr/reports',
  path: '/sdr/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SdrCallsRoute = SdrCallsRouteImport.update({
  id: '/sdr/calls',
  path: '/sdr/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsPreparationRoute = MeetingsPreparationRouteImport.update({
  id: '/meetings/preparation',
  path: '/meetings/preparation',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmDealsRoute = CrmDealsRouteImport.update({
  id: '/crm/deals',
  path: '/crm/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmContactsRoute = CrmContactsRouteImport.update({
  id: '/crm/contacts',
  path: '/crm/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmCompaniesRoute = CrmCompaniesRouteImport.update({
  id: '/crm/companies',
  path: '/crm/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamsRoute = AdminTeamsRouteImport.update({
  id: '/admin/teams',
  path: '/admin/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSolutionsRoute = AdminSolutionsRouteImport.update({
  id: '/admin/solutions',
  path: '/admin/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/admin/clients',
  path: '/admin/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/admin/billing',
  path: '/admin/billing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/drive': typeof DriveRoute
  '/income-calculator': typeof IncomeCalculatorRoute
  '/integrations': typeof IntegrationsRoute
  '/intelligence': typeof IntelligenceRoute
  '/onboarding': typeof OnboardingRoute
  '/preferences': typeof PreferencesRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/solutions': typeof AdminSolutionsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/users': typeof AdminUsersRoute
  '/crm/companies': typeof CrmCompaniesRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/crm/deals': typeof CrmDealsRoute
  '/meetings/preparation': typeof MeetingsPreparationRoute
  '/sdr/calls': typeof SdrCallsRoute
  '/sdr/reports': typeof SdrReportsRoute
  '/sdr/shared': typeof SdrSharedRoute
  '/meetings/': typeof MeetingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/drive': typeof DriveRoute
  '/income-calculator': typeof IncomeCalculatorRoute
  '/integrations': typeof IntegrationsRoute
  '/intelligence': typeof IntelligenceRoute
  '/onboarding': typeof OnboardingRoute
  '/preferences': typeof PreferencesRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/solutions': typeof AdminSolutionsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/users': typeof AdminUsersRoute
  '/crm/companies': typeof CrmCompaniesRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/crm/deals': typeof CrmDealsRoute
  '/meetings/preparation': typeof MeetingsPreparationRoute
  '/sdr/calls': typeof SdrCallsRoute
  '/sdr/reports': typeof SdrReportsRoute
  '/sdr/shared': typeof SdrSharedRoute
  '/meetings': typeof MeetingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/drive': typeof DriveRoute
  '/income-calculator': typeof IncomeCalculatorRoute
  '/integrations': typeof IntegrationsRoute
  '/intelligence': typeof IntelligenceRoute
  '/onboarding': typeof OnboardingRoute
  '/preferences': typeof PreferencesRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/solutions': typeof AdminSolutionsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/users': typeof AdminUsersRoute
  '/crm/companies': typeof CrmCompaniesRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/crm/deals': typeof CrmDealsRoute
  '/meetings/preparation': typeof MeetingsPreparationRoute
  '/sdr/calls': typeof SdrCallsRoute
  '/sdr/reports': typeof SdrReportsRoute
  '/sdr/shared': typeof SdrSharedRoute
  '/meetings/': typeof MeetingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/drive'
    | '/income-calculator'
    | '/integrations'
    | '/intelligence'
    | '/onboarding'
    | '/preferences'
    | '/profile'
    | '/settings'
    | '/tasks'
    | '/admin/billing'
    | '/admin/clients'
    | '/admin/solutions'
    | '/admin/teams'
    | '/admin/users'
    | '/crm/companies'
    | '/crm/contacts'
    | '/crm/deals'
    | '/meetings/preparation'
    | '/sdr/calls'
    | '/sdr/reports'
    | '/sdr/shared'
    | '/meetings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/drive'
    | '/income-calculator'
    | '/integrations'
    | '/intelligence'
    | '/onboarding'
    | '/preferences'
    | '/profile'
    | '/settings'
    | '/tasks'
    | '/admin/billing'
    | '/admin/clients'
    | '/admin/solutions'
    | '/admin/teams'
    | '/admin/users'
    | '/crm/companies'
    | '/crm/contacts'
    | '/crm/deals'
    | '/meetings/preparation'
    | '/sdr/calls'
    | '/sdr/reports'
    | '/sdr/shared'
    | '/meetings'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/drive'
    | '/income-calculator'
    | '/integrations'
    | '/intelligence'
    | '/onboarding'
    | '/preferences'
    | '/profile'
    | '/settings'
    | '/tasks'
    | '/admin/billing'
    | '/admin/clients'
    | '/admin/solutions'
    | '/admin/teams'
    | '/admin/users'
    | '/crm/companies'
    | '/crm/contacts'
    | '/crm/deals'
    | '/meetings/preparation'
    | '/sdr/calls'
    | '/sdr/reports'
    | '/sdr/shared'
    | '/meetings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DriveRoute: typeof DriveRoute
  IncomeCalculatorRoute: typeof IncomeCalculatorRoute
  IntegrationsRoute: typeof IntegrationsRoute
  IntelligenceRoute: typeof IntelligenceRoute
  OnboardingRoute: typeof OnboardingRoute
  PreferencesRoute: typeof PreferencesRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminSolutionsRoute: typeof AdminSolutionsRoute
  AdminTeamsRoute: typeof AdminTeamsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  CrmCompaniesRoute: typeof CrmCompaniesRoute
  CrmContactsRoute: typeof CrmContactsRoute
  CrmDealsRoute: typeof CrmDealsRoute
  MeetingsPreparationRoute: typeof MeetingsPreparationRoute
  SdrCallsRoute: typeof SdrCallsRoute
  SdrReportsRoute: typeof SdrReportsRoute
  SdrSharedRoute: typeof SdrSharedRoute
  MeetingsIndexRoute: typeof MeetingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/income-calculator': {
      id: '/income-calculator'
      path: '/income-calculator'
      fullPath: '/income-calculator'
      preLoaderRoute: typeof IncomeCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drive': {
      id: '/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof DriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings/': {
      id: '/meetings/'
      path: '/meetings'
      fullPath: '/meetings/'
      preLoaderRoute: typeof MeetingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sdr/shared': {
      id: '/sdr/shared'
      path: '/sdr/shared'
      fullPath: '/sdr/shared'
      preLoaderRoute: typeof SdrSharedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sdr/reports': {
      id: '/sdr/reports'
      path: '/sdr/reports'
      fullPath: '/sdr/reports'
      preLoaderRoute: typeof SdrReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sdr/calls': {
      id: '/sdr/calls'
      path: '/sdr/calls'
      fullPath: '/sdr/calls'
      preLoaderRoute: typeof SdrCallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings/preparation': {
      id: '/meetings/preparation'
      path: '/meetings/preparation'
      fullPath: '/meetings/preparation'
      preLoaderRoute: typeof MeetingsPreparationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/deals': {
      id: '/crm/deals'
      path: '/crm/deals'
      fullPath: '/crm/deals'
      preLoaderRoute: typeof CrmDealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/contacts': {
      id: '/crm/contacts'
      path: '/crm/contacts'
      fullPath: '/crm/contacts'
      preLoaderRoute: typeof CrmContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/companies': {
      id: '/crm/companies'
      path: '/crm/companies'
      fullPath: '/crm/companies'
      preLoaderRoute: typeof CrmCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teams': {
      id: '/admin/teams'
      path: '/admin/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/solutions': {
      id: '/admin/solutions'
      path: '/admin/solutions'
      fullPath: '/admin/solutions'
      preLoaderRoute: typeof AdminSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/admin/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/admin/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DriveRoute: DriveRoute,
  IncomeCalculatorRoute: IncomeCalculatorRoute,
  IntegrationsRoute: IntegrationsRoute,
  IntelligenceRoute: IntelligenceRoute,
  OnboardingRoute: OnboardingRoute,
  PreferencesRoute: PreferencesRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminSolutionsRoute: AdminSolutionsRoute,
  AdminTeamsRoute: AdminTeamsRoute,
  AdminUsersRoute: AdminUsersRoute,
  CrmCompaniesRoute: CrmCompaniesRoute,
  CrmContactsRoute: CrmContactsRoute,
  CrmDealsRoute: CrmDealsRoute,
  MeetingsPreparationRoute: MeetingsPreparationRoute,
  SdrCallsRoute: SdrCallsRoute,
  SdrReportsRoute: SdrReportsRoute,
  SdrSharedRoute: SdrSharedRoute,
  MeetingsIndexRoute: MeetingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
